### PR TITLE
Fixes #4 and #8

### LINKED ISSUE #4: Improve the ui of the portfolio card when modal is close
it will be good if UI can be changed into more like this 
https://dribbble.com/shots/6247653-Info-Cards-Animation

### LINKED ISSUE #8: Navbar links not mapped correctly
**Describe the bug**
The links in the Navbar are not mapped/linked correctly.
- `Home` is linked to `#hero`
- `Skill` is linked to `#about`
- `Portfolio` is linked to `#skills`
- `Experience` is linked to `#services`

**Expected behaviour**
- `Home` should be linked to `#home`
- `Skill` should be linked to `#skills`
- `Portfolio` should be linked to `#portfolio`
- `Experience` should be linked to `#experience`

### PR DESCRIPTION
**Pull request by Siddhesh-Agarwal**
- Fixes #4 
- Fixes #8

### CODE REVIEW

**Comment by Siddhesh-Agarwal** [comment]
I am open to making more changes (if required)

**Review by bilalakhter — CHANGES_REQUESTED** [review]
hover effect seems good but i think it maybe better to not change color for portfolio code also the anchor tags are still same as they were

**Comment by Siddhesh-Agarwal** [comment]
The Anchor tags have changed (they were linked to different elements before).

>  think it maybe better to not change color for portfolio code

So, should I change the on-hover colour to some shade of grey?

**Comment by bilalakhter** [comment]
yes

**Comment by Siddhesh-Agarwal** [comment]
@bilalakhter Done. Please review the changes.

**Comment by bilalakhter** [comment]
the reference anchor tags are still same anyways glad you contributed i will close this PR now

**Review by bilalakhter — APPROVED** [review]

**Pull request merged**
